development:
  token_validity_period: 4
  default_email: 'Restaurant Admin <restaurant@admin.com>'
  email_id: 'achyut@vinsol.com'
  email_password: 'grayfullbuster'

production:
  default_email: 'Restaurant Owner <restaurant@admin.com>'

test:
  default_email: 'Restaurant Tester <restaurant@admin.com>'
